### ISSUE TITLE
Question about training a generative model and generating images with a different dataset.

### ISSUE THREAD

**Issue by CVKim** [sjtuplayer/anomalydiffusion#69]
Traceback (most recent call last):
  File "/storage/research/workspaces/anomalydiffusion/generate_mask.py", line 110, in <module>
    model.embedding_manager.load('logs/mask-checkpoints/%s-%s/checkpoints/embeddings.pt'%(sample_name,anomaly_name))
  File "/storage/research/workspaces/anomalydiffusion/ldm/modules/embedding_manager.py", line 175, in load
    ckpt = torch.load(ckpt_path, map_location='cpu')
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'logs/mask-checkpoints/grid-glue/checkpoints/embeddings.pt'

---
cmd

CUDA_VISIBLE_DEVICES=2 python run-mvtec.py --data_path=/storage/image_datasets/mvtec_anomaly_detection

---------------------------------------------------------------------------+
I am using the run_mvtec.py code to train an image generation model for each defect class in the MVTec-AD test set using a 2-fold method.

However, when I run the command as described, it seems that the process doesn't proceed because there is no checkpoint. How should I handle this situation?

Should I use actual_resume as it is if I want to start a new training process? I'm still learning about generative models, so I'm having difficulty understanding the overall process.

What I want to achieve is to split the MVTec-AD test set into 2 folds and then create a new generative model for each fold to generate 100 images + masks.

I would really appreciate your help with this!

**Comment by sjtuplayer** [comment]
Hi, run-mvtec.py contains both the training code and testing code. The problem happens because the training code do not save the corresponding checkpoints, you can have a check.

**Comment by CVKim** [comment]
Hello, @sjtuplayer 

I am trying to train a new dataset using run_mvtec.py. When the train_mask.py function is called for the first time in run_mvtec.py, does it use the entire mvtec-ad dataset located in the path I specified with opt.data_path?

For example, if the opt.data_path = /root/mvtec-custom folder contains files like hazelnut/test/0~10.png, does it train on all 0~10 files without splitting them or dividing them into train/val sets, using them all for training?

The reason I'm asking is that after training and sampling the mvtec-ad dataset using the path I specified with opt.data_path, the resulting mask images seem to be generated in a similar way each time. I'm wondering if it's actually training on the entire dataset I provided. I couldn't find any place in the code where the dataset is being split or divided (e.g., // 2, // 3).

**Comment by bye111** [comment]
您好，请问您解决No such file or directory: 'logs/mask-checkpoints/grid-glue/checkpoints/embeddings.pt'了吗，我也遇到了同样问题。是否是train_mask途中没有在相应文件夹下生成embedding.pt文件logs/mask-checkpoints/%s-%s/checkpoints/embeddings.pt，我仅生成了logs/mask-checkpoints/%s-%s/checkpoints/last.ckpt
